basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /sd/cpu:
    get:
      consumes:
      - application/json
      description: cpu利用率检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: cpu利用率检查
      tags:
      - ServiceDiscovery
  /sd/disk:
    get:
      consumes:
      - application/json
      description: 磁盘空间检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 磁盘空间检查
      tags:
      - ServiceDiscovery
  /sd/health:
    get:
      consumes:
      - application/json
      description: 服务健康检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 服务健康检查
      tags:
      - ServiceDiscovery
  /sd/ram:
    get:
      consumes:
      - application/json
      description: 内存利用率检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 内存利用率检查
      tags:
      - ServiceDiscovery
swagger: "2.0"
