basePath: '{{.BasePath}}'
definitions:
  cluster.CreateRequest:
    properties:
      api_host:
        type: string
      api_token:
        type: string
      name:
        type: string
    type: object
  controllers.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /sd/cpu:
    get:
      consumes:
      - application/json
      description: cpu利用率检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: cpu利用率检查
      tags:
      - ServiceDiscovery
  /sd/disk:
    get:
      consumes:
      - application/json
      description: 磁盘空间检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 磁盘空间检查
      tags:
      - ServiceDiscovery
  /sd/health:
    get:
      consumes:
      - application/json
      description: 服务健康检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 服务健康检查
      tags:
      - ServiceDiscovery
  /sd/ram:
    get:
      consumes:
      - application/json
      description: 内存利用率检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 内存利用率检查
      tags:
      - ServiceDiscovery
  /v1/cluster:
    post:
      consumes:
      - application/json
      description: 通过k8s master api token 添加集群
      parameters:
      - description: 用户登录状态的token
        in: header
        name: Authorization
        required: true
        type: string
      - description: '{}'
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/cluster.CreateRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 添加集群
      tags:
      - cluster
swagger: "2.0"
